In [3]:
import numpy as np
b = np.array([[1,2,3,4],[5,6,7,8]], dtype=complex)
print(b)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 7.+0.j 8.+0.j]]


In [8]:
np.empty((3,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.zeros((3,4),dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [9]:
np.random.rand(2,3)

array([[0.14532615, 0.29464922, 0.35775439],
       [0.87763449, 0.41499857, 0.19370713]])

In [11]:
np.linspace(2,3,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [15]:
a=np.arange(1,21,2)
print(a)
b=a.reshape(5,2)
b
a.dot(b)

[ 1  3  5  7  9 11 13 15 17 19]


ValueError: shapes (10,) and (5,2) not aligned: 10 (dim 0) != 5 (dim 0)

In [17]:
d = np.random.random((2,5))
print(d)
print(d.min())
print(d.max())
print(d.sum(axis=0))
d.sum(axis=1)

[[0.27357989 0.66503869 0.27102422 0.03029276 0.23741191]
 [0.39786294 0.78801808 0.56981407 0.6044259  0.76392457]]
0.030292764740605715
0.7880180825416463
[0.67144283 1.45305678 0.84083829 0.63471866 1.00133649]


array([1.47734749, 3.12404556])

In [25]:
dim_arr1=np.arange(4).reshape(2,2)
print(dim_arr1)
dim_arr2=np.array([[5,10],[10,10]])
print(dim_arr2)
print(f"Transpose: \n {np.transpose(dim_arr1)}\n")
print(f"Inner product: \n {np.inner(dim_arr1,dim_arr2)}\n")
print(f"Cross product: \n {np.cross(dim_arr1,dim_arr2)}\n")
print(f"Dot product: \n {np.dot(dim_arr1,dim_arr2)}\n")

[[0 1]
 [2 3]]
[[ 5 10]
 [10 10]]
Transpose: 
 [[0 2]
 [1 3]]

Inner product: 
 [[10 10]
 [40 50]]

Cross product: 
 [ -5 -10]

Dot product: 
 [[10 10]
 [40 50]]



In [29]:
arr = np.floor(10*np.random.random((3,4)))
print(arr)

print(arr.ravel())

print(arr.reshape(6,2))

print(arr.T)

print(arr.shape)
print(arr.T.shape)

[[9. 4. 9. 5.]
 [6. 3. 0. 6.]
 [5. 2. 1. 4.]]
[9. 4. 9. 5. 6. 3. 0. 6. 5. 2. 1. 4.]
[[9. 4.]
 [9. 5.]
 [6. 3.]
 [0. 6.]
 [5. 2.]
 [1. 4.]]
[[9. 6. 5.]
 [4. 3. 2.]
 [9. 0. 1.]
 [5. 6. 4.]]
(3, 4)
(4, 3)


In [30]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6).reshape(2,3)

print("arr1:\\n",arr1)
print("arr2:\\n",arr2)

print("\\n Using vstack and hstack\\n")

print("vertical stacking:\\n",np.vstack((arr1,arr2)))

print("horizontal stacking:\\n",np.hstack((arr1,arr2)))

print("\\n Using column_stack and row_stack\\n")

print("Horizontal stacking:\\n",np.column_stack((arr1,arr2)))

print("Vertical stacking:\\n",np.row_stack((arr1,arr2)))

arr1:\n [[0 1 2]
 [3 4 5]]
arr2:\n [[0 1 2]
 [3 4 5]]
\n Using vstack and hstack\n
vertical stacking:\n [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
horizontal stacking:\n [[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
\n Using column_stack and row_stack\n
Horizontal stacking:\n [[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
Vertical stacking:\n [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [34]:
arr = np.arange(20).reshape((2,10))
print(arr)
arr2 = arr.reshape(4,5)
print(arr2)

print("\\n Along horizontal axis:\\n")

print(np.hsplit(arr,5))
print("arr is now divided into 5 different arrays.\\n")

print(np.hsplit(arr,(1,7)))
print(" arr is split after the second and the fifth column\\n")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
\n Along horizontal axis:\n
[array([[ 0,  1],
       [10, 11]]), array([[ 2,  3],
       [12, 13]]), array([[ 4,  5],
       [14, 15]]), array([[ 6,  7],
       [16, 17]]), array([[ 8,  9],
       [18, 19]])]
arr is now divided into 5 different arrays.\n
[array([[ 0],
       [10]]), array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]]), array([[ 7,  8,  9],
       [17, 18, 19]])]
 arr is split after the second and the fifth column\n


In [40]:
arr = np.arange(20).reshape((2,10))
print(arr)
arr2 = arr.reshape(4,5)
print(arr2)
print("\\nAlong vertical axis:\\n")
print(np.vsplit(arr,2))
print("\\n arr2 is split after the second row\\n")

print(np.vsplit(arr2,4))
print("\\n arr2 is split after the second row\\n")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
\nAlong vertical axis:\n
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]
\n arr2 is split after the second row\n
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]
\n arr2 is split after the second row\n


In [43]:
arr = np.arange(20).reshape((2,10))
arr2 = arr.reshape(4,5)
print(arr2)

print("\\nUsing array_split:")
print("\\n",np.array_split(arr2,2,0))
print("\\n",np.array_split(arr2,2,1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
\nUsing array_split:
\n [array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]
\n [array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])]


In [44]:
 arr1 = np.arange(20)
 arr2 = arr1.view()
 
 print(arr2 is arr1)
 arr2.shape = (5,4)
 print(arr1.shape)
 
 arr2[0] = 100
 
 print(arr1[0])

False
(20,)
100
